[project]
name = "week-odd-or-even"
version = "0.1.1"
description = "这周是单周还是双周"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "nicegui>=2.24",
    "pywebview>=6.0",
    "questionary>=2.1",
]
